# -*- coding: utf-8 -*-
"""TCGCSV_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYk412e7PVmyvFhqwWyWCBMrcYt4bh-3
"""

import os
import requests
import datetime
import pandas as pd
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
import json

# Write temporary client and token JSONs from secrets
with open("oauth_client.json", "w") as f:
    f.write(os.environ["GDRIVE_OAUTH_CLIENT_JSON"])

with open("credentials.json", "w") as f:
    f.write(os.environ["GDRIVE_OAUTH_TOKEN_JSON"])

# Authenticate
gauth = GoogleAuth()
gauth.LoadClientConfigFile("oauth_client.json")
gauth.LoadCredentialsFile("credentials.json")
if gauth.credentials is None:
    gauth.LocalWebserverAuth()
    gauth.SaveCredentialsFile("credentials.json")
else:
    gauth.Authorize()
drive = GoogleDrive(gauth)

def upload_to_drive(local_path, filename, parent_folder_id):
    file_drive = drive.CreateFile({
        'title': filename,
        'parents': [{'id': parent_folder_id}]
    })
    file_drive.SetContentFile(local_path)
    file_drive.Upload()
    print(f"Uploaded {filename}")

def preprocess(filepath, set_name):
    df = pd.read_csv(filepath)

    df = df.drop(['productId','name','categoryId','groupId','imageCount','extCardText','directLowPrice','subTypeName','extNumber',	'extRarity',	'extCardType',	'extHP',	'extStage',	'extAttack1',	'extAttack2',	'extWeakness',	'extResistance'	,'extRetreatCost'], axis=1, errors='ignore')

    df = df[df['cleanName'].str.contains(f'{set_name}')]

    return df

sets = {
    'Surging Sparks': 'https://tcgcsv.com/tcgplayer/3/23651/ProductsAndPrices.csv',
    'Prismatic Evolutions': 'https://tcgcsv.com/tcgplayer/3/23821/ProductsAndPrices.csv',
    'Destined Rivals': 'https://tcgcsv.com/tcgplayer/3/24269/ProductsAndPrices.csv',
    'Black Bolt': 'https://tcgcsv.com/tcgplayer/3/24325/ProductsAndPrices.csv',
    'White Flare': 'https://tcgcsv.com/tcgplayer/3/24380/ProductsAndPrices.csv',
    '151': 'https://tcgcsv.com/tcgplayer/3/23237/ProductsAndPrices.csv',
    'Shrouded Fable': 'https://tcgcsv.com/tcgplayer/3/23529/ProductsAndPrices.csv',
    'Paldean Fates': 'https://tcgcsv.com/tcgplayer/3/23353/ProductsAndPrices.csv',
    'Mega Evolution': 'https://tcgcsv.com/tcgplayer/3/24380/ProductsAndPrices.csv'
}

folders = {
    'Surging Sparks': '18-wC2BiaclCUvvnwI9ZZTm-dbK11Klgc',
    'Prismatic Evolutions': '1_kQN6JI4pnw2NrzbpP3NNKPIW850Pm-M',
    'Destined Rivals': '19VTDSiA0j3DHbUGjmBMTasQOgZEWDBCL',
    'Black Bolt': '1jm_kB_uah03xd2ALxfL-GL3ldQBvVYVh',
    'White Flare': '1ITWm-bv1hJz5_rQucFGQWb6_Nk2bKL7j',
    '151': '1h9rboDOOZipLC4geGzrDoPOugt5NcuSz',
    'Shrouded Fable': '1wW-PKmzJqfUVKuUcJ18MJIVOzCEiMQeo',
    'Paldean Fates': '1IBs19s4YogQI0RHFopUqTMqSyjU5ofHc',
    'Mega Evolution': '1XEs4ifVAGKQmku82KoJERagGPEc6whaR'
    
}

today = datetime.date.today().isoformat()
for set_name, url in sets.items():
    filename = f"{set_name.replace(' ', '_')}_{today}.csv"
    local_path = f"/tmp/{filename}"

    response = requests.get(url)
    response.raise_for_status()
    with open(local_path, 'wb') as f:
        f.write(response.content)

    df = preprocess(local_path, set_name)
    df.to_csv(local_path, index=False)

    drive_folder = folders[set_name]
    upload_to_drive(local_path, filename, drive_folder)
